[theme]
primaryColor="#A61C8F"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#3752A6"
font="sans serif"

[server]
maxUploadSize=200
enableXsrfProtection=true

[browser]
gatherUsageStats=false
